redis_stream:
  default_key_pattern: "{{.Prefix}}:{{.Schema}}:{{.Table}}"
  tables:
    public.shipments: '{{.Prefix}}:{{.Field "id"}}'

redis_json:
  default_key_pattern: '{{.Prefix}}:{{.Schema}}:{{.Table}}:{{.Field "id"}}'
  tables:
    public.us_states: 'us_states:{{.Field "id"}}'
    public.organizations: 'organizations:{{.Field "id"}}'

meilisearch:
  tables:
    public.us_states: us_states
    public.customers: customers
