redis_stream:
  sync_all: true
  default_key_pattern: "{{.Prefix}}:{{.Schema}}:{{.Table}}"
  tables:
    public.orders: "{{.Prefix}}:orders:{{.Field \"status\"}}"

redis_json:
  default_key_pattern: "{{.Prefix}}:{{.Schema}}:{{.Table}}:{{.Field \"id\"}}"
  tables:
    public.users: "{{.Prefix}}:users:{{.Field \"id\"}}"
    public.orders: "{{.Prefix}}:orders:{{.Field \"customer_id\"}}:{{.Field \"id\"}}"

meilisearch:
  tables:
    public.products: products
    public.users: users
